from .extract import Extract
import datetime as dt 
import pandas as pd 
import isodate
import os 
from dotenv import load_dotenv

load_dotenv()

mapping = {
    'videoId':'videoid',
    'publishedAt': 'published_at',
    'channelTitle': 'channel_title',
    'viewCount': 'viewcount',
    'likeCount': 'likecount',
    'commentCount': 'commentcount',
    'categoryId': 'categoryid'
}

def Transform(dataframe, api_key=None):
    if api_key is None:
        api_key = os.getenv('YOUTUBE_API_KEY')
    if not api_key:
        raise ValueError("API key is missing or empty")
    """
    Transforms and cleans the raw YouTube Data API

    :param dataframe:  DataFrame generated by the Extract function.
    :returns: A cleaned pandas DataFrame with proper types and formatted values.
    :rtype: pandas.DataFrame
    """
    dataframe = dataframe.drop_duplicates()
    dataframe[["viewCount", "likeCount", "commentCount"]] = dataframe[["viewCount", "likeCount", "commentCount"]].astype(int)
    dataframe["publishedAt"] = pd.to_datetime(dataframe["publishedAt"])
    dataframe["duration"] = dataframe["duration"].apply(isodate.parse_duration)
    dataframe["duration"] = pd.to_timedelta(dataframe["duration"])

    # Change datatype to appropriate 
    dataframe['title'] = dataframe['title'].astype('string')
    dataframe['channelTitle'] = dataframe['channelTitle'].astype('string')
    dataframe['categoryId'] = dataframe['categoryId'].astype('int')

    #lower name
    dataframe = dataframe.rename(columns=mapping)
 
    return dataframe

